site_name: auto-operations

# readthedocs   material
theme:  material
use_directory_urls: true

docs_dir: 'docs'


pages:
- 首页: 'index.md'
- 资产探测:
    - '资产探测-nmap': 'assets_scanning/nmap.md'
    - '端口探测-telnetlib': 'assets_scanning/telnetlib.md'
    - '登录探测': 'assets_scanning/login.md'
    - '主机资产信息获取': 'assets_scanning/host_asset_info.md'
    - '网络资产信息获取': 'assets_scanning/net_assets_info.md'
    - 'docker容器信息获取': 'assets_scanning/docker.md'
    - '总结-工程逻辑图': 'assets_scanning/zj.md'
- 自动化任务:
    - '自动化任务-ansible': 'automated_task/ansible.md'
- 其它:
    - 'yaml文件配置和读取': 'extra/yaml_use.md'


# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/hightfly01/imoocc-notebook'


# Copyright
copyright: 'Copyright (c) 2018 hightfly'


extra:
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  author:
    github: 'hightfly01'


# Extensions
markdown_extensions:
  #高亮
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
